### ISSUE TITLE
Make SRML compatible

### ISSUE THREAD

**Issue by DracoClaw** [SatyPardus/BetterBuildPublic#1]
Seeing as the loader functions have been lost/stripped out. Might this be a good time to make the mod for SRML

**Comment by SatyPardus** [comment]
It's very easy to implement. I just didn't want to deal with possibly issues that come with third party loaders.

If you want to implement it, here is the code I used:
```cs
public class SRML : ModEntryPoint
{
    private GameObject m_GameObject;

    public override void PreLoad()
    {
        if (m_GameObject != null) return;

        HarmonyInstance.PatchAll();

        if (!Directory.Exists(BetterBuildMod.ModDataPath))
            Directory.CreateDirectory(BetterBuildMod.ModDataPath);

        m_GameObject = new GameObject("BetterBuildMod");
        m_GameObject.AddComponent<BetterBuildMod>();

        GameObject.DontDestroyOnLoad(m_GameObject);
    }
}
```

I did not use any features of SRML as I hate to rely on third party mods while developing my own.
